packages:
  - packages/*

allowBuilds:
  unrs-resolver: true

catalog:
  '@ianvs/prettier-plugin-sort-imports': ^4.7.1
  '@rolldown/pluginutils': ^1.0.1
  '@types/node': ^24.12.2
  '@typescript-eslint/parser': ^8.58.1
  '@typescript-eslint/utils': ^8.58.1
  eslint: ^10.2.0
  eslint-config-prettier: ^10.1.8
  eslint-import-resolver-typescript: ^4.4.4
  eslint-plugin-import: ^2.32.0
  eslint-plugin-prettier: ^5.5.5
  eslint-plugin-react: ^7.37.5
  eslint-plugin-react-hooks: ^7.0.1
  jiti: ^2.6.1
  prettier: ^3.8.2
  publint: ^0.3.21
  srvx: ^0.11.15
  tsdown: ^0.21.10
  typescript: ^6.0.3
  typescript-eslint: ^8.58.1
  vite: ^8.0.14

catalogMode: prefer

publicHoistPattern:
  - '@ianvs/prettier-plugin-sort-imports'
